#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo ""
  echo "syntax: start [PROJECT]"
  echo ""
  echo "PROJECT is the relative path to project from current folder (actually: $PWD)"
  echo "Project can also be '.' for current folder"
  echo ""
  exit 1
fi


if [ "$1" == "." ];then
  PROJECT=$(basename $PWD)
  FOLDER=$PWD
else
  PROJECT=$(basename $1)
  FOLDER=$PWD/$1
fi

echo "$PROJECT"
docker run --rm -it -d \
  --name go-dev-$PROJECT \
  -u $(id -u ${USER}):$(id -g ${USER}) \
  -v $FOLDER:/home \
  -w /home \
  -e GO111MODULE=on \
  -e GOCACHE=/tmp \
  golang

