#!/bin/bash

if [ "$#" -eq 1 ]; then
  CONTAINER=go-dev-$1
else
  CONTAINER=$(docker ps -aqf "name=go-dev-*")
fi

if [ -z "$CONTAINER" ];then
  echo "No running container"
else
  docker stop $CONTAINER
fi

