#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo ""
  echo "syntax: test <project_name>"
  echo ""
  echo "Replace <project_name>"
  echo ""
  exit 1
fi

PROJECT=$1

docker exec go-dev-$PROJECT go test ./...
